tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "autoconf"
brew "automake"
brew "bash-completion"
brew "cmake"
brew "colordiff"
brew "composer"
brew "coreutils", link: false
brew "docutils"
brew "lame"
brew "ffmpeg"
brew "fontconfig"
brew "gdbm"
brew "gettext"
brew "gist"
brew "git"
brew "libffi"
brew "gnupg"
brew "hub"
brew "jq"
brew "libdvdcss"
brew "libevent"
brew "libogg"
brew "libvorbis"
brew "libvpx"
brew "libxslt"
brew "lynx"
brew "mas"
brew "md5sha1sum"
brew "node"
brew "pandoc"
brew "parallel"
brew "pv"
brew "sqlite"
brew "python"
brew "qt"
brew "ruby"
brew "siege"
brew "spidermonkey", link: false
brew "theora"
brew "tree"
brew "watch"
brew "wdiff"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"
cask "1password-cli"
cask "alfred"
cask "appzapper"
cask "arq"
cask "atext"
cask "bartender"
cask "docker"
cask "dropbox"
cask "firefox"
cask "focus"
cask "gpg-suite"
cask "iterm2"
cask "licecap"
cask "notion"
cask "webstorm"
cask "slack"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "zoomus"
cask "homebrew/cask-fonts/font-fira-mono-for-powerline"
cask "homebrew/cask-fonts/font-menlo-for-powerline"
mas "1Password", id: 443987910
mas "iA Writer Classic", id: 439623248
mas "Keynote", id: 409183694
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
